### ISSUE TITLE
classes of >16bit Unicode characters

### ISSUE THREAD

**Issue by didier31** [jflex-de/jflex#179] opened 2015-03-16 22:48 UTC
Hi again the jflex team,

I've profited of jflex 1.6 to uncomment classes like [\u116C0-\u116C9] in my lexer.
Talking about this class, my test reveals that jflex generated lexers that this class in particular (but some others too) includes some ponctuation signs characters like  ';' and ':' 

If you need an example, you can refer to the one in https://github.com/jflex-de/jflex/issues/178.

In this example,
it affects IDENTIFIER lexeme in whatever the case modes.
For example, string "myInterger:Integer;" is computed as a whole identifier thanks to  [\u116C0-\u116C9]. This class is part of definition of macro, NUMBER_DECIMAL8.

Best regards
Didier.

**Comment by lsf37** [comment] 2015-03-17 06:16
Ah well, looks like we might need a 1.6.2 release..

Will need a few days this time before I can take a closer look, am travelling at the moment. Maybe @sarowe has time before.

**Comment by didier31** [comment] 2015-03-17 09:56
No worry. I'm not hurry. It is just an hobby project of my own.

Happy if I may contribute to make your release more mature.

Have a good journey

Best regards

**Comment by lsf37** [comment] 2015-03-21 07:10
Thanks, am back now ;-) I've confirmed a smaller example:

```
%%

%public
%class Test

%int
%debug

TAKRI_DIGIT = [\u116C0-\u116C9]
LETTER = [a-zA-Z]

%%

{LETTER} ({LETTER}|{TAKRI_DIGIT})*    {  /* identifier */  return 1; }
[^]                                   {  /* single char */ return 2; }
```
Input: `myInterger:Integer;`

Steps:
```
> jflex -q 179.flex
> javac Test.java 
> java Test input.txt 
match: --myInterger:Integer;--
action [14] { /* identifier */  return 1; }
1
match: --\u000A--
action [15] { /* single char */ return 2; }
2
-1
```

**Comment by lsf37** [comment] 2015-03-21 07:23
This time the problem is just a syntax error: `\u116C0` doesn't mean code point `116C0`, but instead `\u116C` followed by the character `0`. This means your character class includes `\u115C`, `0-\u116C`, and `9`, which includes the `:` that gets matched in the identifier.

To get code point `116C0`, you can either write `\U0116C0` or `\u{116C0}`:

```
%%

%public
%class Test

%int
%debug

TAKRI_DIGIT = [\U0116C0-\U0116C9]
LETTER = [a-zA-Z]

%%

{LETTER} ({LETTER}|{TAKRI_DIGIT})*    {  /* identifier */  return 1; }
[^]                                   {  /* single char */ return 2; }
```

Output:
```
> jflex -q 179-2.flex 
> javac Test.java && java Test input.txt 
match: --myInterger--
action [14] { /* identifier */  return 1; }
1
match: --:--
action [15] { /* single char */ return 2; }
2
match: --Integer--
action [14] { /* identifier */  return 1; }
1
match: --;--
action [15] { /* single char */ return 2; }
2
match: --\u000A--
action [15] { /* single char */ return 2; }
2
-1
```

**Comment by didier31** [comment] 2015-03-23 10:11
Tanks a lot !

All is fine now : no regression with my tests.

Regards
Didier.

**Comment by lsf37** [comment] 2015-03-23 11:05
Cool, then I'll close this one.

**Comment by didier31** [comment] 2015-03-23 16:46
Hum.. this singularity is not obvious and not detected as a syntax error.
Others like me could have the same trouble.

**Comment by lsf37** [comment] 2015-03-23 21:20
It's legal syntax, it just doesn't mean what it looks it might mean. Changing it would break scanners that are currently correct.

I think I'll add a warning to the manual that the `\u{..}` form is the safest, because it's easy to see where it starts and ends. I actually found it easily because of syntax highlighting, but that depends on which editor you're using.

**Comment by didier31** [comment] 2015-03-24 19:43
I guess, otherwise, it would break the backward compatibility for some lexer's specifications.

It is wise like this, I think.

Anyway, I'm a very happy user.
I believe sincerely it is the most complete and powerful lexer builder for java.
And the unique one I can use to respect Ada 2005 language specs.

**Closed** 2015-04-12 12:02 UTC
Labels: bug, invalid
