### ISSUE TITLE
jflex-1.6.1: syntax error in LexScan.java: orphaned default

### ISSUE THREAD

**Issue by romildo** [jflex-de/jflex#192] opened 2015-09-14 11:37 UTC
Trying to compile `jflex-1.6.1` on Gentoo Linux is giving me the following error:

    compile:
        [mkdir] Created dir: /tmp/portage/dev-java/jflex-1.6.1/work/jflex-1.6.1/build/classes
        [javac] Compiling 71 source files to /tmp/portage/dev-java/jflex-1.6.1/work/jflex-1.6.1/build/classes
        [javac] /tmp/portage/dev-java/jflex-1.6.1/work/jflex-1.6.1/build/generated-sources/jflex/LexScan.java:2656: error: orphaned default
        [javac]         default: 
        [javac]         ^
        [javac] /tmp/portage/dev-java/jflex-1.6.1/work/jflex-1.6.1/build/generated-sources/jflex/LexScan.java:3469: error: 'else' without 'if'
        [javac]           else {
        [javac]           ^
        [javac] 2 errors

**Comment by regisd** [comment] 2015-09-14 13:04
Duplicate of #171 I believe

**Closed by regisd** 2015-09-14 13:04 UTC
Labels: bug, duplicate
