### ISSUE TITLE
jflex-maven-plugin - Regeneration of previously generated classes changes modification date of the output file

### ISSUE THREAD

**Issue by bintom** [jflex-de/jflex#720] opened 2020-02-25 10:30 UTC
When I `mvn package` already packaged module I got a log informing `MyJflexFile.java is up to date`, but I noticed its modification date has changed. This triggers Maven compiler plugin to recompile the module. I suggest to not change the modification date if content does not change.

**Comment by regisd** [comment] 2020-12-18 16:03
There is a PR to work around this bug in Maven https://github.com/jflex-de/jflex/pull/765

**Comment by lsf37** [comment] 2023-01-07 21:42
I'll leave this open -- #765 does not fix it, it just provides specific dates for the jar file.

**Comment by lsf37** [comment] 2023-01-20 22:02
So I tried this and couldn't reproduce it. When I do `mvn generate-sources` or `mvn package` and get an "up to date" output from the plugin, the file modification time of the generated target sources does not change and sources are also not recompiled ("Nothing to compile - all classes are up to date" from the maven-compiler-plugin) for me.

`mvn package` does re-run the test suite and re-package the compiled classes, but it does not recompile for me. 

Looking at the code, it does explicitly check for modification time in the plugin (that's when it generates the "up to date" output) and returns without further action from that path.

It's possible that this was indeed a more general maven bug that has been fixed since.

I'll close this one for now, but if you keep seeing this behaviour, please do feel free to re-open.

**Closed by lsf37** 2023-01-20 22:02 UTC
Labels: enhancement
