### ISSUE TITLE
How to use "Long" instead of "Integer" to avoid NumberFormatException 

### ISSUE THREAD

**Issue by nobeh** [jflex-de/jflex#191] opened 2015-08-20 06:50 UTC
We have a language syntax [ABS.cf][1] that uses [BNFC][2]. Here is how I generate the tooling for scanner/lexer/parser:

```bash
$ bnfc -m --java -o src/main/java --jflex -p bnfc src/main/resources/abs.cf
$ mvn exec:java -Dexec.mainClass="java_cup.Main" -Dexec.args="-expect 1000 -package bnfc.abs src/main/java/bnfc/abs/abs.cup"
$ mvn exec:java -Dexec.mainClass="jflex.Main" -Dexec.args="--jlex src/main/java/bnfc/abs/Yylex"
```

Everything works fine for many test cases that we have. However, we have an issue with "integer" literals. The origin ABS language does not have a strict definition of an integer (might be questionable). So, let's just consider the following line in ABS:

```
Int s = 500050000000;
```

Then I simply get the following exception:

```
[SEVERE] Compile error found at line 49 near:
	{}5000500000
[SEVERE] Compliation failed: java.lang.NumberFormatException: For input string: "500050000000"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:583)
	at java.lang.Integer.<init>(Integer.java:867)
	at bnfc.abs.Yylex.next_token(Yylex.java:793)
	at java_cup.runtime.lr_parser.scan(lr_parser.java:349)
	at java_cup.runtime.lr_parser.parse(lr_parser.java:578)
	at jabsc.Compiler.parseSource(Compiler.java:175)
	at jabsc.Compiler.compile(Compiler.java:115)
	at jabsc.Compiler.compile(Compiler.java:86)
	at jabsc.cli.CompilerCommand.run(CompilerCommand.java:30)
	at jabsc.cli.Bootstrap.main(Bootstrap.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Thread.java:745)
```

What am I missing? Is there a chance `Long` can be used instead of `Integer`? How?

Thanks.

[1]: https://github.com/CrispOSS/jabsc/blob/master/src/main/resources/abs.cf
[2]: http://bnfc.digitalgrammars.com/

**Comment by nobeh** [comment] 2015-08-20 07:23
I think I've found the root cause. It's actually BNFC that by default binds the category of `Integer` in its grammar definition *always* to an instance `java.lang.Integer`.

**Comment by lsf37** [comment] 2015-08-20 08:25
Yes, looks like the problem is on the BNFC side. Are you happy for me to close the issue?

**Comment by nobeh** [comment] 2015-08-20 09:14
Please do so. Sorry for any inconvenience.

**Comment by lsf37** [comment] 2015-08-20 09:23
No worries

**Closed by lsf37** 2015-08-20 09:23 UTC
